-- Sequenza per l'ID utente
CREATE SEQUENCE SEQ_UTENTE
START WITH 1
MINVALUE 1
INCREMENT BY 1;

-- Sequenza per l'ID gate
CREATE SEQUENCE SEQ_GATE
START WITH 1
MINVALUE 1
INCREMENT BY 1;

-- Sequenza per l'ID prenotazione
CREATE SEQUENCE SEQ_PRENOTAZIONE
START WITH 1
MINVALUE 1
INCREMENT BY 1;

-- Sequenza per l'ID volo
CREATE SEQUENCE SEQ_VOLO
START WITH 1
MINVALUE 1
INCREMENT BY 1;
